version: '3.8'

services:
  apache:
    build: . 
    container_name: lamp_biblioteca 
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
      
    depends_on:
      - database
    
  database:
    image: mariadb:latest
    container_name: maria_db_biblioteca
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: "root" 
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "biblioteca" 
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    driver: local